name: ASYOMIN
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93772
title: The Journey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1013'
    - '#ffffff'
    - '#647c8f'
    - '#b8c6dc'
    - '#7b0427'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
